#!/usr/bin/env python3
"""
ingest_snomed_sdoh.py — Generate a Banyan export document for the SNOMED CT
SDOH slice referenced by the Gravity SDOH Clinical Care STU 2.3 value sets.

Reads:
  backend/data/gravity/vsac_oid_manifest.json
  backend/data/gravity/vsac/*.json  (VSAC expansion cache from fetch_vsac_expansions.py)

Writes:
  backend/data/gravity/snomed_sdoh.banyan.json

Network:
  Calls the UMLS REST API to traverse SNOMED CT parent relationships.
  Requires a UMLS API key (set UMLS_API_KEY env var or pass --api-key).

Algorithm
---------
1.  Collect seed SNOMED codes from the Diagnoses and Goals value sets in the
    VSAC cache.  Procedures and Service Requests are excluded — those are
    clinical interventions, not the social-need conditions the crosswalk is
    built around.

2.  For each seed code, walk up the SNOMED parent chain iteratively via the
    UMLS REST API (source=SNOMEDCT_US, endpoint=parents).

3.  Stop ascending when a concept is in the STOP_SET.  The stop-set concepts
    are included as nodes but their parents are not traversed.  They become
    the visible L1 tier in the Banyan tree, connected to $ROOT$.

4.  Collect all unique concepts (seeds + ancestors + stop-set) and all
    parent-child relationships, then build a Banyan 1.1 export document.

Stop-set (5 concepts — confirmed design decision)
---------
  404684003  Clinical finding
  243796009  Situation with explicit context
  48176007   Social context
  363787002  Observable entity
  71388002   Procedure

Polyhierarchy
-------------
SNOMED concepts can have multiple parents.  All parent links are preserved.
A concept with two parents will appear under both in the Banyan tree.

Source ID convention
--------------------
  http://snomed.info/sct|{code}

No database writes.  Review the output before importing.

Import with:
    python utils/import_graph.py backend/data/gravity/snomed_sdoh.banyan.json
"""

from __future__ import annotations

import argparse
import json
import os
import re
import sys
import time
import urllib.error as _err
import urllib.request as _req
from datetime import datetime, timezone
from pathlib import Path

# ---------------------------------------------------------------------------
# Paths and constants
# ---------------------------------------------------------------------------

REPO_ROOT     = Path(__file__).resolve().parent.parent
MANIFEST_PATH = REPO_ROOT / "data" / "gravity" / "vsac_oid_manifest.json"
VSAC_CACHE    = REPO_ROOT / "data" / "gravity" / "vsac"
OUTPUT_PATH   = REPO_ROOT / "data" / "gravity" / "snomed_sdoh.banyan.json"

UMLS_BASE       = "https://uts-ws.nlm.nih.gov/rest"
SNOMED_SOURCE   = "SNOMEDCT_US"
SNOMED_SYSTEM   = "http://snomed.info/sct"
ROOT_SOURCE_ID  = "$ROOT$"
REQUEST_DELAY   = 0.25   # seconds between UMLS API calls
MAX_RETRIES     = 2

# Activity slugs whose SNOMED codes we include as seeds.
# Procedures and Service Requests are excluded (clinical interventions).
SEED_ACTIVITIES = {"diagnoses", "goals", "findings"}

# Stop-set: include as nodes, do not traverse above.
STOP_SET: dict[str, str] = {
    "404684003": "Clinical finding",
    "243796009": "Situation with explicit context",
    "48176007":  "Social context",
    "363787002": "Observable entity",
    "71388002":  "Procedure",
}

GRAPH_NAME = "SNOMED CT SDOH Slice"
GRAPH_NOTES = (
    "SNOMED CT concepts referenced by the Gravity SDOH Clinical Care IG STU 2.3 "
    "value sets (Diagnoses and Goals activities), plus their ancestor chain to the "
    "SNOMED stop-set.  Source: UMLS/NLM SNOMEDCT_US via UMLS REST API. "
    "Generated by utils/ingest_snomed_sdoh.py."
)


# ---------------------------------------------------------------------------
# UMLS API helpers
# ---------------------------------------------------------------------------

def _umls_get(url: str) -> dict:
    req = _req.Request(url, headers={"Accept": "application/json"})
    for attempt in range(1, MAX_RETRIES + 1):
        try:
            with _req.urlopen(req, timeout=15) as resp:
                return json.loads(resp.read().decode())
        except _err.HTTPError as exc:
            if exc.code == 404:
                return {}   # concept not found / no parents
            if attempt == MAX_RETRIES:
                raise
            time.sleep(1)
        except Exception:
            if attempt == MAX_RETRIES:
                raise
            time.sleep(1)
    return {}


def get_parents(code: str, api_key: str) -> list[dict]:
    """
    Return immediate SNOMED parents for a concept code.
    Each entry: { "ui": "<code>", "name": "<preferred term>" }
    """
    url = (
        f"{UMLS_BASE}/content/current/source/{SNOMED_SOURCE}"
        f"/{code}/parents?apiKey={api_key}"
    )
    data = _umls_get(url)
    results = data.get("result", [])
    if not isinstance(results, list):
        return []
    return [{"ui": r["ui"], "name": r["name"]} for r in results if r.get("ui")]


def get_preferred_name(code: str, api_key: str) -> str:
    """Fetch preferred term for a SNOMED concept (used for stop-set nodes)."""
    url = (
        f"{UMLS_BASE}/content/current/source/{SNOMED_SOURCE}"
        f"/{code}?apiKey={api_key}"
    )
    data = _umls_get(url)
    result = data.get("result", {})
    return result.get("name", code)


# ---------------------------------------------------------------------------
# Seed collection from VSAC cache
# ---------------------------------------------------------------------------

def collect_seeds(manifest: dict) -> dict[str, str]:
    """
    Return {snomed_code: display} for all unique SNOMED codes from Diagnoses
    and Goals value sets across all 28 domains.

    Uses the local VSAC cache — no network calls.
    """
    seeds: dict[str, str] = {}
    domains = manifest.get("domains", {})

    for domain_key, domain in domains.items():
        for vs_label, oid in domain.get("value_sets", {}).items():
            if not oid:
                continue
            # Determine activity slug
            activity = re.sub(r"\s*\([^)]+\)", "", vs_label).strip()
            activity = re.sub(r"[^a-z0-9]+", "-", activity.lower()).strip("-")
            if activity not in SEED_ACTIVITIES:
                continue

            cache_file = VSAC_CACHE / f"{oid}.json"
            if not cache_file.exists():
                print(f"  WARNING: cache miss {oid} ({domain_key}/{activity}) — run fetch_vsac_expansions.py first")
                continue

            with cache_file.open(encoding="utf-8") as f:
                cached = json.load(f)

            for entry in cached.get("codes", []):
                if entry.get("system") == SNOMED_SYSTEM and entry.get("code"):
                    seeds[entry["code"]] = entry.get("display", entry["code"])

    return seeds


# ---------------------------------------------------------------------------
# Ancestor traversal
# ---------------------------------------------------------------------------

def build_concept_graph(
    seeds: dict[str, str],
    api_key: str,
) -> tuple[dict[str, str], dict[str, set[str]]]:
    """
    Walk SNOMED parents from each seed code up to the stop-set.

    Returns:
      concepts : { code → preferred_name }
      parents  : { child_code → {parent_code, ...} }

    Traversal rules:
    - When we reach a stop-set code, we add it to concepts but do not fetch
      its parents (traversal stops there).
    - All parent-child edges are recorded (polyhierarchy preserved).
    """
    concepts: dict[str, str] = {}    # code → name
    parents: dict[str, set[str]] = {}  # child → set of parent codes
    visited: set[str] = set()          # codes whose parents we've already fetched
    queue: list[str] = list(seeds.keys())

    # Pre-populate seeds
    for code, display in seeds.items():
        concepts[code] = display

    # Pre-populate stop-set names (we know them, no API needed)
    for code, name in STOP_SET.items():
        if code not in concepts:
            concepts[code] = name

    total_calls = 0

    while queue:
        code = queue.pop(0)
        if code in visited:
            continue
        visited.add(code)

        # Stop-set: record the node but do not climb further
        if code in STOP_SET:
            continue

        parent_list = get_parents(code, api_key)
        total_calls += 1
        if total_calls % 50 == 0:
            print(f"    ... {total_calls} UMLS calls, {len(concepts)} concepts so far")

        for p in parent_list:
            p_code = p["ui"]
            p_name = p["name"]

            # Record the parent concept
            if p_code not in concepts:
                concepts[p_code] = p_name

            # Record the parent edge
            if code not in parents:
                parents[code] = set()
            parents[code].add(p_code)

            # Enqueue parent for its own traversal (unless stop-set or visited)
            if p_code not in visited and p_code not in STOP_SET:
                queue.append(p_code)

        if queue:
            time.sleep(REQUEST_DELAY)

    print(f"  UMLS calls: {total_calls}  |  concepts: {len(concepts)}  |  edges: {sum(len(v) for v in parents.values())}")
    return concepts, parents


# ---------------------------------------------------------------------------
# Banyan document builder
# ---------------------------------------------------------------------------

def source_id(code: str) -> str:
    return f"{SNOMED_SYSTEM}|{code}"


def build_export_doc(
    concepts: dict[str, str],
    parents: dict[str, set[str]],
    seeds: dict[str, str],
) -> dict:
    nodes: list[dict] = []
    links: list[dict] = []

    # Classify each concept
    stop_codes   = set(STOP_SET.keys())
    seed_codes   = set(seeds.keys())
    # Codes that have no parents in our graph (i.e., their only parents are stop-set
    # nodes or they ARE stop-set nodes) — these connect to $ROOT$ via the stop-set.

    for code, name in concepts.items():
        is_stop  = code in stop_codes
        is_seed  = code in seed_codes
        is_anc   = not is_stop and not is_seed

        metadata: dict = {
            "code_system":       "SNOMED CT",
            "code_system_short": "SNOMED",
            "code":              code,
            "display":           name,
        }
        if is_stop:
            metadata["is_stop_node"] = True
        if is_seed:
            metadata["is_gravity_seed"] = True

        nodes.append({
            "source_id": source_id(code),
            "name":      name,
            "metadata":  metadata,
        })

    # Stop-set nodes connect to $ROOT$
    for code in stop_codes:
        if code in concepts:
            links.append({
                "from_source_id": ROOT_SOURCE_ID,
                "to_source_id":   source_id(code),
                "link_type_name": "HIERARCHICAL",
            })

    # All other parent-child edges
    for child_code, parent_codes in parents.items():
        for parent_code in parent_codes:
            if parent_code not in concepts:
                continue   # pruned ancestor outside our graph
            links.append({
                "from_source_id": source_id(parent_code),
                "to_source_id":   source_id(child_code),
                "link_type_name": "HIERARCHICAL",
            })

    return {
        "banyan_export_version": "1.1",
        "exported_at": datetime.now(timezone.utc).isoformat(),
        "graph": {"name": GRAPH_NAME, "notes": GRAPH_NOTES},
        "nodes": nodes,
        "links": links,
        "cross_graph_links": [],
    }


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------

def main() -> None:
    parser = argparse.ArgumentParser(
        description="Build a Banyan export document for the SNOMED CT SDOH slice."
    )
    parser.add_argument(
        "--api-key",
        default=os.environ.get("UMLS_API_KEY", ""),
        help="UMLS API key (default: UMLS_API_KEY env var)",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Collect and print seed codes without calling UMLS",
    )
    args = parser.parse_args()

    if not MANIFEST_PATH.exists():
        print(f"ERROR: manifest not found at {MANIFEST_PATH}", file=sys.stderr)
        sys.exit(1)

    if not VSAC_CACHE.exists() or not any(VSAC_CACHE.glob("*.json")):
        print(
            "ERROR: VSAC cache is empty.  Run fetch_vsac_expansions.py first.",
            file=sys.stderr,
        )
        sys.exit(1)

    with MANIFEST_PATH.open(encoding="utf-8") as f:
        manifest = json.load(f)

    print("Collecting SNOMED seed codes from VSAC cache ...")
    seeds = collect_seeds(manifest)
    print(f"  Unique SNOMED seeds : {len(seeds)}")

    if args.dry_run:
        for code, display in sorted(seeds.items()):
            print(f"  {code}  {display}")
        return

    if not args.api_key:
        print(
            "ERROR: UMLS API key required.\n"
            "  Set UMLS_API_KEY environment variable, or pass --api-key.",
            file=sys.stderr,
        )
        sys.exit(1)

    print(f"Traversing SNOMED parents to stop-set (delay={REQUEST_DELAY}s/call) ...")
    concepts, parents = build_concept_graph(seeds, args.api_key)

    print("Building Banyan export document ...")
    doc = build_export_doc(concepts, parents, seeds)

    stop_nodes  = [n for n in doc["nodes"] if n["metadata"].get("is_stop_node")]
    seed_nodes  = [n for n in doc["nodes"] if n["metadata"].get("is_gravity_seed")]
    anc_nodes   = [n for n in doc["nodes"]
                   if not n["metadata"].get("is_stop_node")
                   and not n["metadata"].get("is_gravity_seed")]
    root_links  = [lk for lk in doc["links"] if lk["from_source_id"] == ROOT_SOURCE_ID]
    hier_links  = [lk for lk in doc["links"] if lk["from_source_id"] != ROOT_SOURCE_ID]

    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    with OUTPUT_PATH.open("w", encoding="utf-8") as f:
        json.dump(doc, f, indent=2, ensure_ascii=False)

    print(f"\nWritten: {OUTPUT_PATH}")
    print(f"  Stop-set nodes (L1)    : {len(stop_nodes)}")
    print(f"  Ancestor nodes         : {len(anc_nodes)}")
    print(f"  Seed nodes (Gravity)   : {len(seed_nodes)}")
    print(f"  Total nodes            : {len(doc['nodes'])}")
    print(f"  $ROOT$->stop-set links : {len(root_links)}")
    print(f"  HIERARCHICAL links     : {len(hier_links)}")
    print(f"  Total links            : {len(doc['links'])}")


if __name__ == "__main__":
    main()
