#!/usr/bin/env python3
"""
ingest_icd10.py — Generate a Banyan export document for the ICD-10-CM SDOH
slice referenced by the Gravity SDOH Clinical Care STU 2.3 value sets.

Reads:
  backend/data/gravity/vsac_oid_manifest.json
  backend/data/gravity/vsac/*.json  (VSAC expansion cache from fetch_vsac_expansions.py)

Writes:
  backend/data/gravity/icd10_sdoh.banyan.json

Network:
  Calls the UMLS REST API to traverse ICD-10-CM parent relationships.
  Requires a UMLS API key (set UMLS_API_KEY env var or pass --api-key).

Algorithm
---------
1.  Collect seed ICD-10-CM codes from Diagnoses value sets in the VSAC cache.
    Goals and Service Requests are excluded — those are SNOMED-only activities.

2.  For each seed code, walk up the ICD-10-CM parent chain via the UMLS REST
    API (source=ICD10CM, endpoint=parents).

3.  Stop ascending when a code is a 3-character category code (matches the
    pattern ^[A-Z]\\d\\d$, e.g. Z59, T74, E63).  These are auto-discovered
    during traversal; no pre-defined stop list is needed.  Category-level
    nodes become the visible L1 tier, connected to $ROOT$.

Stop-set detection
------------------
  ICD-10-CM category codes follow the pattern ^[A-Z]\\d\\d$ (one letter, two
  digits).  Examples: Z55, Z59, Z60, Z63, T74, T76, E63, Z91.

  The Gravity Diagnoses value sets span several ICD-10-CM blocks:
    Z55-Z65  Socioeconomic / psychosocial circumstances (primary SDOH block)
    Z71, Z73, Z76, Z91  Other Z-categories (counseling, lifestyle, history)
    T74, T76  Adult and child abuse / neglect (interpersonal violence domain)
    E63       Other nutritional deficiencies (food insecurity domain)

  Stopping at the 3-character category level yields ~15 L1 nodes with Z55-Z65
  as the dominant cluster (~10 nodes), matching the "stop at block level"
  intent of Option A.

ICD-10-CM hierarchy notes
--------------------------
  ICD-10-CM uses a strict hierarchy (no polyhierarchy).  Each specific code
  has exactly one parent at the subcategory/category level.  Traversal is
  therefore a simple path, not a DAG.

Source ID convention
--------------------
  http://hl7.org/fhir/sid/icd-10-cm|{code}

No database writes.  Review the output before importing.

Import with:
    python utils/import_graph.py backend/data/gravity/icd10_sdoh.banyan.json
"""

from __future__ import annotations

import argparse
import json
import os
import re
import sys
import time
import urllib.error as _err
import urllib.request as _req
from datetime import datetime, timezone
from pathlib import Path

# ---------------------------------------------------------------------------
# Paths and constants
# ---------------------------------------------------------------------------

REPO_ROOT     = Path(__file__).resolve().parent.parent
MANIFEST_PATH = REPO_ROOT / "data" / "gravity" / "vsac_oid_manifest.json"
VSAC_CACHE    = REPO_ROOT / "data" / "gravity" / "vsac"
OUTPUT_PATH   = REPO_ROOT / "data" / "gravity" / "icd10_sdoh.banyan.json"

UMLS_BASE      = "https://uts-ws.nlm.nih.gov/rest"
ICD10_SOURCE   = "ICD10CM"
ICD10_SYSTEM   = "http://hl7.org/fhir/sid/icd-10-cm"
ROOT_SOURCE_ID = "$ROOT$"
REQUEST_DELAY  = 0.25   # seconds between UMLS API calls
MAX_RETRIES    = 2

# Seeds come from Diagnoses value sets only.  ICD-10-CM does not appear in
# Goals or Service Requests (those are SNOMED-only in Gravity STU 2.3).
SEED_ACTIVITIES = {"diagnoses"}

# 3-character category code pattern.  Any parent that matches becomes a stop
# node: it is included in the graph but its own parents are not fetched.
CATEGORY_CODE_RE = re.compile(r"^[A-Z]\d\d$")

GRAPH_NAME = "ICD-10-CM SDOH Slice"
GRAPH_NOTES = (
    "ICD-10-CM codes referenced by the Gravity SDOH Clinical Care IG STU 2.3 "
    "Diagnoses value sets, plus their ancestor chain to the 3-character "
    "category level (Z55, Z59, T74, E63, etc.).  Source: UMLS/NLM ICD10CM "
    "via UMLS REST API.  Generated by utils/ingest_icd10.py."
)


# ---------------------------------------------------------------------------
# UMLS API helpers
# ---------------------------------------------------------------------------

def _umls_get(url: str) -> dict:
    req = _req.Request(url, headers={"Accept": "application/json"})
    for attempt in range(1, MAX_RETRIES + 1):
        try:
            with _req.urlopen(req, timeout=15) as resp:
                return json.loads(resp.read().decode())
        except _err.HTTPError as exc:
            if exc.code == 404:
                return {}   # concept not found / no parents
            if attempt == MAX_RETRIES:
                raise
            time.sleep(1)
        except Exception:
            if attempt == MAX_RETRIES:
                raise
            time.sleep(1)
    return {}


def get_parents(code: str, api_key: str) -> list[dict]:
    """
    Return immediate ICD-10-CM parents for a code.
    Each entry: { "ui": "<code>", "name": "<preferred term>" }
    """
    url = (
        f"{UMLS_BASE}/content/current/source/{ICD10_SOURCE}"
        f"/{code}/parents?apiKey={api_key}"
    )
    data = _umls_get(url)
    results = data.get("result", [])
    if not isinstance(results, list):
        return []
    return [{"ui": r["ui"], "name": r["name"]} for r in results if r.get("ui")]


# ---------------------------------------------------------------------------
# Seed collection from VSAC cache
# ---------------------------------------------------------------------------

def collect_seeds(manifest: dict) -> dict[str, str]:
    """
    Return {icd10_code: display} for all unique ICD-10-CM codes from Diagnoses
    value sets across all 28 domains.

    Uses the local VSAC cache — no network calls.
    """
    seeds: dict[str, str] = {}
    domains = manifest.get("domains", {})

    for domain_key, domain in domains.items():
        for vs_label, oid in domain.get("value_sets", {}).items():
            if not oid:
                continue
            # Determine activity slug from label (strip parenthetical system list)
            activity = re.sub(r"\s*\([^)]+\)", "", vs_label).strip()
            activity = re.sub(r"[^a-z0-9]+", "-", activity.lower()).strip("-")
            if activity not in SEED_ACTIVITIES:
                continue

            cache_file = VSAC_CACHE / f"{oid}.json"
            if not cache_file.exists():
                print(
                    f"  WARNING: cache miss {oid} ({domain_key}/{activity})"
                    f" — run fetch_vsac_expansions.py first"
                )
                continue

            with cache_file.open(encoding="utf-8") as f:
                cached = json.load(f)

            for entry in cached.get("codes", []):
                if entry.get("system") == ICD10_SYSTEM and entry.get("code"):
                    seeds[entry["code"]] = entry.get("display", entry["code"])

    return seeds


# ---------------------------------------------------------------------------
# Ancestor traversal
# ---------------------------------------------------------------------------

def build_concept_graph(
    seeds: dict[str, str],
    api_key: str,
) -> tuple[dict[str, str], dict[str, str], set[str]]:
    """
    Walk ICD-10-CM parents from each seed up to the 3-character category level.

    Returns:
      concepts : { code → preferred_name }
      parents  : { child_code → parent_code }   (strict hierarchy, one parent)

    Traversal rules:
    - When we reach a 3-character category code, we add it to concepts and
      mark it as a stop node; its parents are not fetched.
    - Seeds that are already 3-character codes are treated as stop nodes
      immediately and connect to $ROOT$.
    """
    concepts: dict[str, str] = {}      # code → display name
    parents:  dict[str, str] = {}      # child → parent (one-to-one)
    stop_codes: set[str] = set()       # auto-discovered category codes
    visited: set[str] = set()
    queue: list[str] = list(seeds.keys())

    # Pre-populate seeds
    for code, display in seeds.items():
        concepts[code] = display
        if CATEGORY_CODE_RE.match(code):
            stop_codes.add(code)

    total_calls = 0

    while queue:
        code = queue.pop(0)
        if code in visited:
            continue
        visited.add(code)

        # Stop nodes: do not climb further
        if code in stop_codes:
            continue

        parent_list = get_parents(code, api_key)
        total_calls += 1
        if total_calls % 50 == 0:
            print(f"    ... {total_calls} UMLS calls, {len(concepts)} concepts so far")

        for p in parent_list:
            p_code = p["ui"]
            p_name = p["name"]

            # Skip structural/aggregate codes (block ranges like "Z55-Z65",
            # chapter codes that UMLS may occasionally surface)
            if "-" in p_code:
                # Block-level range code — not a clinical code, skip
                continue

            # Record the parent concept
            if p_code not in concepts:
                concepts[p_code] = p_name

            # Record the parent edge (ICD-10-CM: strict hierarchy, one parent)
            parents[code] = p_code

            # Mark 3-char codes as stop nodes
            if CATEGORY_CODE_RE.match(p_code):
                stop_codes.add(p_code)

            # Enqueue parent unless already visited or stop
            if p_code not in visited and p_code not in stop_codes:
                queue.append(p_code)

        if queue:
            time.sleep(REQUEST_DELAY)

    print(
        f"  UMLS calls: {total_calls}  |  concepts: {len(concepts)}"
        f"  |  category (stop) nodes: {len(stop_codes)}"
    )
    return concepts, parents, stop_codes


# ---------------------------------------------------------------------------
# Banyan document builder
# ---------------------------------------------------------------------------

def source_id(code: str) -> str:
    return f"{ICD10_SYSTEM}|{code}"


def build_export_doc(
    concepts:   dict[str, str],
    parents:    dict[str, str],
    seeds:      dict[str, str],
    stop_codes: set[str],
) -> dict:
    nodes: list[dict] = []
    links: list[dict] = []

    seed_codes = set(seeds.keys())

    for code, name in concepts.items():
        is_stop = code in stop_codes
        is_seed = code in seed_codes and not is_stop

        metadata: dict = {
            "code_system":       "ICD-10-CM",
            "code_system_short": "ICD-10",
            "code":              code,
            "display":           name,
        }
        if is_stop:
            metadata["is_stop_node"] = True
        if is_seed:
            metadata["is_gravity_seed"] = True

        nodes.append({
            "source_id": source_id(code),
            "name":      name,
            "metadata":  metadata,
        })

    # Category (stop) nodes connect to $ROOT$
    for code in stop_codes:
        if code in concepts:
            links.append({
                "from_source_id": ROOT_SOURCE_ID,
                "to_source_id":   source_id(code),
                "link_type_name": "HIERARCHICAL",
            })

    # All other parent-child edges
    for child_code, parent_code in parents.items():
        if parent_code not in concepts:
            continue
        links.append({
            "from_source_id": source_id(parent_code),
            "to_source_id":   source_id(child_code),
            "link_type_name": "HIERARCHICAL",
        })

    return {
        "banyan_export_version": "1.1",
        "exported_at": datetime.now(timezone.utc).isoformat(),
        "graph": {"name": GRAPH_NAME, "notes": GRAPH_NOTES},
        "nodes": nodes,
        "links": links,
        "cross_graph_links": [],
    }


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------

def main() -> None:
    parser = argparse.ArgumentParser(
        description="Build a Banyan export document for the ICD-10-CM SDOH slice."
    )
    parser.add_argument(
        "--api-key",
        default=os.environ.get("UMLS_API_KEY", ""),
        help="UMLS API key (default: UMLS_API_KEY env var)",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Collect and print seed codes without calling UMLS",
    )
    args = parser.parse_args()

    if not MANIFEST_PATH.exists():
        print(f"ERROR: manifest not found at {MANIFEST_PATH}", file=sys.stderr)
        sys.exit(1)

    if not VSAC_CACHE.exists() or not any(VSAC_CACHE.glob("*.json")):
        print(
            "ERROR: VSAC cache is empty.  Run fetch_vsac_expansions.py first.",
            file=sys.stderr,
        )
        sys.exit(1)

    with MANIFEST_PATH.open(encoding="utf-8") as f:
        manifest = json.load(f)

    print("Collecting ICD-10-CM seed codes from VSAC cache ...")
    seeds = collect_seeds(manifest)
    print(f"  Unique ICD-10-CM seeds : {len(seeds)}")

    if args.dry_run:
        for code, display in sorted(seeds.items()):
            print(f"  {code}  {display}")
        return

    if not args.api_key:
        print(
            "ERROR: UMLS API key required.\n"
            "  Set UMLS_API_KEY environment variable, or pass --api-key.",
            file=sys.stderr,
        )
        sys.exit(1)

    print(f"Traversing ICD-10-CM parents to category codes (delay={REQUEST_DELAY}s/call) ...")
    concepts, parents, stop_codes = build_concept_graph(seeds, args.api_key)

    print("Building Banyan export document ...")
    doc = build_export_doc(concepts, parents, seeds, stop_codes)

    stop_nodes = [n for n in doc["nodes"] if n["metadata"].get("is_stop_node")]
    seed_nodes = [n for n in doc["nodes"] if n["metadata"].get("is_gravity_seed")]
    anc_nodes  = [
        n for n in doc["nodes"]
        if not n["metadata"].get("is_stop_node")
        and not n["metadata"].get("is_gravity_seed")
    ]
    root_links = [lk for lk in doc["links"] if lk["from_source_id"] == ROOT_SOURCE_ID]
    hier_links = [lk for lk in doc["links"] if lk["from_source_id"] != ROOT_SOURCE_ID]

    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    with OUTPUT_PATH.open("w", encoding="utf-8") as f:
        json.dump(doc, f, indent=2, ensure_ascii=False)

    print(f"\nWritten: {OUTPUT_PATH}")
    print(f"  Category (L1) nodes    : {len(stop_nodes)}")
    print(f"  Ancestor nodes         : {len(anc_nodes)}")
    print(f"  Seed nodes (Gravity)   : {len(seed_nodes)}")
    print(f"  Total nodes            : {len(doc['nodes'])}")
    print(f"  $ROOT$->category links : {len(root_links)}")
    print(f"  HIERARCHICAL links     : {len(hier_links)}")
    print(f"  Total links            : {len(doc['links'])}")

    print("\nCategory (L1) nodes discovered:")
    for n in sorted(stop_nodes, key=lambda x: x["source_id"]):
        print(f"  {n['metadata']['code']}  {n['name']}")


if __name__ == "__main__":
    main()
