#!/usr/bin/env python3
"""
ingest_snomed_sr.py — Generate a Banyan export document for SNOMED CT
service-request procedure codes referenced by the Gravity SDOH IG STU 2.3.

Reads:
  backend/data/gravity/vsac_oid_manifest.json
  backend/data/gravity/vsac/*.json  (VSAC expansion cache)

Writes:
  backend/data/gravity/snomed_sr.banyan.json

No network calls.  No database writes.  Review the output before importing.

This utility produces a FLAT graph — all 965 unique SNOMED CT procedure codes
are leaf nodes directly under $ROOT$.  Hierarchy traversal via the UMLS API
is intentionally omitted: the service-request codes are clinical procedure
concepts whose SNOMED hierarchy is large and not needed for the crosswalk use
case (linking Gravity L2 activity nodes to the procedures they recommend).

HCPCS Level II codes (CMS public domain, 7 unique codes) are included by
default.  CPT codes are excluded — they are AMA-proprietary and require a
separate license.

Source ID conventions
---------------------
  SNOMED CT  :  http://snomed.info/sct|{code}
  HCPCS L2   :  http://www.nlm.nih.gov/research/umls/hcpcs|{code}

Import with:
    python utils/import_graph.py backend/data/gravity/snomed_sr.banyan.json
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from datetime import datetime, timezone
from pathlib import Path

REPO_ROOT     = Path(__file__).resolve().parent.parent
MANIFEST_PATH = REPO_ROOT / "data" / "gravity" / "vsac_oid_manifest.json"
VSAC_CACHE    = REPO_ROOT / "data" / "gravity" / "vsac"
OUTPUT_PATH   = REPO_ROOT / "data" / "gravity" / "snomed_sr.banyan.json"

SNOMED_SYSTEM = "http://snomed.info/sct"
HCPCS_SYSTEM  = "http://www.nlm.nih.gov/research/umls/hcpcs"

GRAPH_NAME = "SNOMED SDOH Service Requests Slice"
GRAPH_NOTES = (
    "SNOMED CT and HCPCS Level II procedure codes referenced by the Gravity SDOH "
    "Clinical Care IG STU 2.3 Service Requests value sets across all 26 social-need "
    "domains.  Flat structure (no SNOMED hierarchy traversal).  CPT codes excluded "
    "(AMA-proprietary license required).  "
    "Generated by utils/ingest_snomed_sr.py."
)


def activity_slug(vs_label: str) -> str:
    label = re.sub(r"\s*\([^)]+\)", "", vs_label).strip()
    return re.sub(r"[^a-z0-9]+", "-", label.lower()).strip("-")


def collect_codes(manifest: dict, include_hcpcs: bool) -> dict[str, dict]:
    """
    Return {source_id: {source_id, name, system}} for all unique SNOMED CT
    (and optionally HCPCS) codes from Service Requests value sets.
    """
    codes: dict[str, dict] = {}
    domains = manifest.get("domains", {})

    for domain_key, domain in domains.items():
        for vs_label, oid in domain.get("value_sets", {}).items():
            if activity_slug(vs_label) != "service-requests":
                continue
            cache_file = VSAC_CACHE / f"{oid}.json"
            if not cache_file.exists():
                print(f"  WARNING: cache miss {oid} ({domain_key}) — run fetch_vsac_expansions.py first",
                      file=sys.stderr)
                continue

            with cache_file.open(encoding="utf-8") as f:
                cached = json.load(f)

            for entry in cached.get("codes", []):
                system = entry.get("system", "")
                code   = entry.get("code", "")
                display = entry.get("display", code)
                if not code:
                    continue

                if "snomed" in system.lower() or system.endswith("/sct"):
                    src = f"{SNOMED_SYSTEM}|{code}"
                    codes[src] = {"source_id": src, "name": display, "system": "SNOMED CT"}
                elif include_hcpcs and ("hcpcs" in system.lower() or "HCPCS" in system):
                    src = f"{HCPCS_SYSTEM}|{code}"
                    codes[src] = {"source_id": src, "name": display, "system": "HCPCS L2"}

    return codes


def build_export(codes: dict[str, dict], include_hcpcs: bool) -> dict:
    nodes = [
        {
            "source_id": c["source_id"],
            "name":      c["name"],
            "metadata":  {"code_system": c["system"]},
        }
        for c in sorted(codes.values(), key=lambda x: x["source_id"])
    ]

    print(f"  Nodes: {len(nodes)} total")
    snomed_n = sum(1 for n in nodes if "snomed" in n["source_id"])
    hcpcs_n  = len(nodes) - snomed_n
    print(f"    SNOMED CT: {snomed_n}")
    if include_hcpcs:
        print(f"    HCPCS L2:  {hcpcs_n}")

    return {
        "banyan_export_version": "1.1",
        "exported_at": datetime.now(timezone.utc).isoformat(),
        "graph": {
            "name":  GRAPH_NAME,
            "notes": GRAPH_NOTES,
        },
        "nodes": nodes,
        "links": [],   # flat — no intra-graph hierarchy links
    }


def main() -> None:
    ap = argparse.ArgumentParser(description="Generate SNOMED SR Banyan export document.")
    ap.add_argument("--no-hcpcs", action="store_true",
                    help="Exclude HCPCS Level II codes (included by default).")
    ap.add_argument("--output", default=str(OUTPUT_PATH),
                    help=f"Output path (default: {OUTPUT_PATH})")
    args = ap.parse_args()

    include_hcpcs = not args.no_hcpcs

    manifest = json.loads(MANIFEST_PATH.read_text(encoding="utf-8"))

    print("Collecting service-request codes from VSAC cache...")
    codes = collect_codes(manifest, include_hcpcs)

    print("Building export document...")
    doc = build_export(codes, include_hcpcs)

    output = Path(args.output)
    output.write_text(json.dumps(doc, indent=2, ensure_ascii=False), encoding="utf-8")
    print(f"Written: {output}")
    print()
    print("Next step:")
    print(f"  python utils/import_graph.py {output}")
    print("  python utils/link_service_requests.py")


if __name__ == "__main__":
    main()
